name: ci

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches: 
    - 'main'
    
env:
  AZURE_WEB_APP: 'MoneyManagerTransaction'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moneymanager:latest
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - 
        name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure WebApp Deployment
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: '${{env.AZURE_WEB_APP}}'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
          images: '${{ secrets.DOCKERHUB_USERNAME }}/moneymanager:latest'
